const String APP_TITLE = 'Список интересных мест';
const String FIRST_SCREEN_TITLE = 'Список\nинтересных мест';
const String FIRST_SCREEN_TITLE_1 = 'С';
const String FIRST_SCREEN_TITLE_2 = 'писок\n';
const String FIRST_SCREEN_TITLE_3 = 'и';
const String FIRST_SCREEN_TITLE_4 = 'нтересных ';
const String FIRST_SCREEN_TITLE_5 = 'м';
const String FIRST_SCREEN_TITLE_6 = 'ест';
const String APP_WILL_BE_HERE= 'Здесь будет наше приложение';
